#!/bin/bash
source /etc/environment
[[ -d /etc/environment.d ]] && source /etc/environment.d/*.conf
if [[ -z $PROG ]]; then
        export PROG=$HOME/Programs
fi
if [[ -f $PROG/tailscale_sync_client_env.sh ]]; then
	source $PROG/tailscale_sync_client_env.sh
else
	source tailscale_sync_client_env.sh
fi

CROND=/etc/cron.d/
CRON_FILE=tailscale_sync_client_cron

CRON_FILE_PATH=$CROND$CRON_FILE

SHELL_FOR_CRON='SHELL=/bin/bash'
HOUR_TIME=60

S="""
$SHELL_FOR_CRON
PROG=$PROG

MAILTO=\"\"

# Past the Hour intervail aliases
P25=\"$(bash $PROG/csvify.sh $(i=25; seq $i $i $(( $HOUR_TIME )) ) )\"
P20=\"$(bash $PROG/csvify.sh $(i=20; seq $i $i $(( $HOUR_TIME )) ) )\"
P15=\"$(bash $PROG/csvify.sh $(i=15; seq $i $i $(( $HOUR_TIME )) ) )\"
P10=\"$(bash $PROG/csvify.sh $(i=10; seq $i $i $(( $HOUR_TIME )) ) )\"
P5=\"$(bash $PROG/csvify.sh $(i=5; seq $i $i $(( $HOUR_TIME )) ) )\"
P2=\"$(bash $PROG/csvify.sh $(i=2; seq $i $i $(( $HOUR_TIME )) ) )\"
"""

if [[ $HOSTNAME == 'ctp-vpn' ]]; then
	sudo rm -rf $CRON_FILE_PATH-*
else
echo """# Generated by: $scriptName
# Generated at: `date`
# Created to sync files in tailscale systems
# Should run once on tailscale setup and then be automatinating itself by updating itself
# No matincace script

$S

""" | sudo tee $CRON_FILE_PATH

fi

for file in "${prog_files_array[@]}"
do
	if [[ $HOSTNAME == 'ctp-vpn' ]]; then
		clients=( $(tailscale status | awk '{print $1" "$2}' | grep -vE "$REGEX_AROUND_HOSTS" ) )
		count=1
		IFS=$'\n'
		for client in ${clients[@]}
		do
			ip_addr=$(echo $client | awk '{print $1}')
			client_name=$(echo $client | awk '{print $2}')
			cmd_str="source \$PROG/all-scripts-exports.sh; [[ \$( ip_exists $ip_addr ) = 'true' ]] && sudo tailscale file cp \$PROG/$file $client_name:"
			echo -e " 5$count *   *   *   *    root	$cmd_str" | sudo tee -a $CRON_FILE_PATH-$client_name
			count=$(( $count + 1))
		done
	else
		cmd_str="bash $PROG/tailscale_sync_client.sh $file $PROG"
		echo -e " 49 *   *   *   *    root	$cmd_str" | sudo tee -a $CRON_FILE_PATH
	fi
done

